-- Trampô: núcleo seguro do ciclo de contratação.
-- A autorização é feita por ownership/RLS; o cliente não é fonte de verdade.
CREATE TABLE IF NOT EXISTS public.proposals (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), job_id uuid NOT NULL REFERENCES public.jobs(id) ON DELETE RESTRICT,
  application_id uuid NOT NULL REFERENCES public.applications(id) ON DELETE RESTRICT, company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE RESTRICT,
  freelancer_id uuid NOT NULL REFERENCES public.freelancers(id) ON DELETE RESTRICT, amount numeric(10,2) NOT NULL CHECK (amount >= 0),
  start_at timestamptz NOT NULL, end_at timestamptz NOT NULL, description text,
  status text NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','ACCEPTED','REJECTED','EXPIRED','CANCELLED')),
  created_at timestamptz NOT NULL DEFAULT now(), accepted_at timestamptz, rejected_at timestamptz, UNIQUE (application_id)
);
CREATE TABLE IF NOT EXISTS public.contracts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), job_id uuid NOT NULL REFERENCES public.jobs(id) ON DELETE RESTRICT,
  company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE RESTRICT, freelancer_id uuid NOT NULL REFERENCES public.freelancers(id) ON DELETE RESTRICT,
  proposal_id uuid NOT NULL UNIQUE REFERENCES public.proposals(id) ON DELETE RESTRICT, amount numeric(10,2) NOT NULL CHECK (amount >= 0),
  platform_fee numeric(10,2) NOT NULL DEFAULT 0 CHECK (platform_fee >= 0), freelancer_amount numeric(10,2) NOT NULL CHECK (freelancer_amount >= 0),
  start_at timestamptz NOT NULL, end_at timestamptz NOT NULL, location text, description text,
  status text NOT NULL DEFAULT 'AWAITING_ACCEPTANCE' CHECK (status IN ('DRAFT','AWAITING_ACCEPTANCE','AWAITING_PAYMENT','PAYMENT_PROCESSING','FUNDS_SECURED','SCHEDULED','IN_PROGRESS','AWAITING_COMPLETION_CONFIRMATION','COMPLETED','RELEASE_PENDING','RELEASED','CANCELLED','DISPUTED','REFUND_PENDING','REFUNDED','NO_SHOW_FREELANCER','NO_SHOW_COMPANY')),
  payment_id uuid REFERENCES public.payments(id), escrow_id uuid REFERENCES public.escrow(id), created_at timestamptz NOT NULL DEFAULT now(), accepted_at timestamptz, started_at timestamptz, completed_at timestamptz, cancelled_at timestamptz
);
CREATE TABLE IF NOT EXISTS public.contract_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), contract_id uuid NOT NULL REFERENCES public.contracts(id) ON DELETE CASCADE, event_type text NOT NULL, actor_id uuid REFERENCES public.users(id), metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.checkins (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), contract_id uuid NOT NULL REFERENCES public.contracts(id) ON DELETE RESTRICT, freelancer_id uuid NOT NULL REFERENCES public.freelancers(id) ON DELETE RESTRICT, method text NOT NULL CHECK (method IN ('PIN','QR_CODE','GPS','MANUAL_ADMIN')), status text NOT NULL DEFAULT 'CONFIRMED' CHECK (status IN ('PENDING','CONFIRMED','REJECTED')), metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (contract_id, freelancer_id));
CREATE TABLE IF NOT EXISTS public.checkouts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), contract_id uuid NOT NULL UNIQUE REFERENCES public.contracts(id) ON DELETE RESTRICT, freelancer_id uuid NOT NULL REFERENCES public.freelancers(id) ON DELETE RESTRICT, status text NOT NULL DEFAULT 'SUBMITTED' CHECK (status IN ('SUBMITTED','CONFIRMED','REJECTED')), note text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.disputes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), contract_id uuid NOT NULL REFERENCES public.contracts(id) ON DELETE RESTRICT, opened_by uuid NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT, reason text NOT NULL, description text NOT NULL, status text NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN','UNDER_REVIEW','RESOLVED','REJECTED')), resolution text CHECK (resolution IS NULL OR resolution IN ('FULL_RELEASE','FULL_REFUND','PARTIAL_RELEASE','PARTIAL_REFUND')), created_at timestamptz NOT NULL DEFAULT now(), resolved_at timestamptz, resolved_by uuid REFERENCES public.users(id));
CREATE TABLE IF NOT EXISTS public.dispute_evidence (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), dispute_id uuid NOT NULL REFERENCES public.disputes(id) ON DELETE CASCADE, submitted_by uuid NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT, kind text NOT NULL CHECK (kind IN ('TEXT','IMAGE','RECEIPT','MESSAGE','CHECKIN','CHECKOUT')), content text NOT NULL CHECK (char_length(content) <= 10000), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.refunds (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), payment_id uuid NOT NULL REFERENCES public.payments(id) ON DELETE RESTRICT, contract_id uuid NOT NULL REFERENCES public.contracts(id) ON DELETE RESTRICT, amount numeric(10,2) NOT NULL CHECK (amount > 0), reason text NOT NULL, status text NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','PROCESSING','COMPLETED','FAILED')), provider_ref text, created_at timestamptz NOT NULL DEFAULT now(), processed_at timestamptz, UNIQUE (payment_id, reason));
CREATE TABLE IF NOT EXISTS public.payment_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), provider text NOT NULL, provider_event_id text NOT NULL, event_type text NOT NULL, payload_hash text NOT NULL, processed_at timestamptz, status text NOT NULL DEFAULT 'RECEIVED' CHECK (status IN ('RECEIVED','PROCESSED','FAILED')), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (provider, provider_event_id));
CREATE TABLE IF NOT EXISTS public.audit_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), actor_id uuid REFERENCES public.users(id), action text NOT NULL, entity_type text NOT NULL, entity_id uuid, before jsonb, after jsonb, reason text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.notifications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE, event_type text NOT NULL, title text NOT NULL, body text NOT NULL, read_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.saved_jobs (user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE, job_id uuid NOT NULL REFERENCES public.jobs(id) ON DELETE CASCADE, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (user_id, job_id));

ALTER TABLE public.proposals ENABLE ROW LEVEL SECURITY; ALTER TABLE public.contracts ENABLE ROW LEVEL SECURITY; ALTER TABLE public.contract_events ENABLE ROW LEVEL SECURITY; ALTER TABLE public.checkins ENABLE ROW LEVEL SECURITY; ALTER TABLE public.checkouts ENABLE ROW LEVEL SECURITY; ALTER TABLE public.disputes ENABLE ROW LEVEL SECURITY; ALTER TABLE public.dispute_evidence ENABLE ROW LEVEL SECURITY; ALTER TABLE public.refunds ENABLE ROW LEVEL SECURITY; ALTER TABLE public.payment_events ENABLE ROW LEVEL SECURITY; ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY; ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY; ALTER TABLE public.saved_jobs ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.is_contract_party(_contract_id uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT EXISTS (SELECT 1 FROM public.contracts c JOIN public.companies co ON co.id = c.company_id JOIN public.freelancers f ON f.id = c.freelancer_id JOIN public.users cu ON cu.id = co.user_id JOIN public.users fu ON fu.id = f.user_id WHERE c.id = _contract_id AND (cu.auth_id = auth.uid() OR fu.auth_id = auth.uid() OR public.has_role(auth.uid(), 'admin'::public.app_role))) $$;
CREATE POLICY "Contract parties can read proposals" ON public.proposals FOR SELECT TO authenticated USING (company_id IN (SELECT id FROM public.companies WHERE user_id IN (SELECT id FROM public.users WHERE auth_id = auth.uid())) OR freelancer_id IN (SELECT id FROM public.freelancers WHERE user_id IN (SELECT id FROM public.users WHERE auth_id = auth.uid())) OR public.has_role(auth.uid(), 'admin'::public.app_role));
CREATE POLICY "Company can create proposals" ON public.proposals FOR INSERT TO authenticated WITH CHECK (company_id IN (SELECT id FROM public.companies WHERE user_id IN (SELECT id FROM public.users WHERE auth_id = auth.uid())));
CREATE POLICY "Contract parties can read contracts" ON public.contracts FOR SELECT TO authenticated USING (public.is_contract_party(id));
CREATE POLICY "Contract parties can read events" ON public.contract_events FOR SELECT TO authenticated USING (public.is_contract_party(contract_id));
CREATE POLICY "Freelancer can create own checkin" ON public.checkins FOR INSERT TO authenticated WITH CHECK (freelancer_id IN (SELECT id FROM public.freelancers WHERE user_id IN (SELECT id FROM public.users WHERE auth_id = auth.uid())) AND public.is_contract_party(contract_id));
CREATE POLICY "Parties can read checkins" ON public.checkins FOR SELECT TO authenticated USING (public.is_contract_party(contract_id));
CREATE POLICY "Freelancer can create checkout" ON public.checkouts FOR INSERT TO authenticated WITH CHECK (freelancer_id IN (SELECT id FROM public.freelancers WHERE user_id IN (SELECT id FROM public.users WHERE auth_id = auth.uid())) AND public.is_contract_party(contract_id));
CREATE POLICY "Parties can read checkouts" ON public.checkouts FOR SELECT TO authenticated USING (public.is_contract_party(contract_id));
CREATE POLICY "Parties can manage disputes" ON public.disputes FOR ALL TO authenticated USING (public.is_contract_party(contract_id)) WITH CHECK (public.is_contract_party(contract_id));
CREATE POLICY "Parties can read evidence" ON public.dispute_evidence FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.disputes d WHERE d.id = dispute_id AND public.is_contract_party(d.contract_id)));
CREATE POLICY "Users can read own notifications" ON public.notifications FOR SELECT TO authenticated USING (user_id IN (SELECT id FROM public.users WHERE auth_id = auth.uid()));
CREATE POLICY "Users can manage saved jobs" ON public.saved_jobs FOR ALL TO authenticated USING (user_id IN (SELECT id FROM public.users WHERE auth_id = auth.uid())) WITH CHECK (user_id IN (SELECT id FROM public.users WHERE auth_id = auth.uid()));
CREATE POLICY "Admins can read audit logs" ON public.audit_logs FOR SELECT TO authenticated USING (public.has_role(auth.uid(), 'admin'::public.app_role));
CREATE POLICY "Admins can read payment events" ON public.payment_events FOR SELECT TO authenticated USING (public.has_role(auth.uid(), 'admin'::public.app_role));
CREATE POLICY "Admins can read refunds" ON public.refunds FOR SELECT TO authenticated USING (public.has_role(auth.uid(), 'admin'::public.app_role));

CREATE OR REPLACE FUNCTION public.create_contract_from_proposal(_proposal_id uuid) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$ DECLARE p public.proposals; new_id uuid; BEGIN SELECT * INTO p FROM public.proposals WHERE id = _proposal_id FOR UPDATE; IF p.id IS NULL OR p.status <> 'ACCEPTED' THEN RAISE EXCEPTION 'proposal_not_accepted'; END IF; IF NOT EXISTS (SELECT 1 FROM public.companies WHERE id = p.company_id AND user_id IN (SELECT id FROM public.users WHERE auth_id = auth.uid())) THEN RAISE EXCEPTION 'not_owner'; END IF; INSERT INTO public.contracts (job_id, company_id, freelancer_id, proposal_id, amount, freelancer_amount, start_at, end_at, description) VALUES (p.job_id, p.company_id, p.freelancer_id, p.id, p.amount, p.amount, p.start_at, p.end_at, p.description) ON CONFLICT (proposal_id) DO UPDATE SET proposal_id = EXCLUDED.proposal_id RETURNING id INTO new_id; INSERT INTO public.contract_events (contract_id, event_type, actor_id) VALUES (new_id, 'CONTRACT_CREATED', (SELECT id FROM public.users WHERE auth_id = auth.uid())); RETURN new_id; END; $$;
REVOKE ALL ON FUNCTION public.create_contract_from_proposal(uuid) FROM PUBLIC, anon; GRANT EXECUTE ON FUNCTION public.create_contract_from_proposal(uuid) TO authenticated;
